// INDEX
export const INDEX_START_TRENDING = 'INDEX_START_TRENDING';
export const INDEX_END_TRENDING = 'INDEX_END_TRENDING';
export const INDEX_ERROR_TRENDING = 'INDEX_ERROR_TRENDING';
export const INDEX_START_NEW_MOVIES = 'INDEX_START_NEW_MOVIES';
export const INDEX_END_NEW_MOVIES = 'INDEX_END_NEW_MOVIES';
export const INDEX_ERROR_NEW_MOVIES = 'INDEX_START_NEW_MOVIES';

// LISTS
export const LIST_START_SORTING = 'LIST_START_SORTING';
export const LIST_END_SORTING = 'LIST_END_SORTING';
export const LIST_ERROR_SORTING = 'LIST_ERROR_SORTING';
export const LIST_START_SEARCHING = 'LIST_START_SEARCHING';
export const LIST_END_SEARCHING = 'LIST_END_SEARCHING';
export const LIST_ERROR_SEARCHING = 'LIST_ERROR_SEARCHING';
export const LIST_SET_SORT_BY = 'LIST_SET_SORT_BY';
export const LIST_SET_PAGE = 'LIST_SET_PAGE';
export const LIST_SET_QUERY = 'LIST_SET_QUERY';

// MOVIE
export const MOVIE_START_FETCHING_INFO = 'MOVIE_START_FETCHING_INFO';
export const MOVIE_END_FETCHING_INFO = 'MOVIE_END_FETCHING_INFO';
export const MOVIE_ERROR_FETCHING_INFO = 'MOVIE_ERROR_FETCHING_INFO';
export const MOVIE_START_FETCHING_CAST = 'MOVIE_START_FETCHING_CAST';
export const MOVIE_END_FETCHING_CAST = 'MOVIE_END_FETCHING_CAST';
export const MOVIE_ERROR_FETCHING_CAST = 'MOVIE_ERROR_FETCHING_CAST';
export const MOVIE_START_FETCHING_RECOMMENDATIONS = 'MOVIE_START_FETCHING_RECOMMENDATIONS';
export const MOVIE_END_FETCHING_RECOMMENDATIONS = 'MOVIE_END_FETCHING_RECOMMENDATIONS';
export const MOVIE_ERROR_FETCHING_RECOMMENDATIONS = 'MOVIE_ERROR_FETCHING_RECOMMENDATIONS';
export const MOVIE_START_FETCHING_VIDEOS = 'MOVIE_START_FETCHING_VIDEOS';
export const MOVIE_END_FETCHING_VIDEOS = 'MOVIE_END_FETCHING_VIDEOS';
export const MOVIE_ERROR_FETCHING_VIDEOS = 'MOVIE_ERROR_FETCHING_VIDEOS';
export const MOVIE_CLEAR_STATE = 'MOVIE_CLEAR_STATE';

// TV SHOW
export const TVSHOW_START_FETCHING_INFO = 'TVSHOW_START_FETCHING_INFO';
export const TVSHOW_END_FETCHING_INFO = 'TVSHOW_END_FETCHING_INFO';
export const TVSHOW_ERROR_FETCHING_INFO = 'TVSHOW_ERROR_FETCHING_INFO';
export const TVSHOW_START_FETCHING_CAST = 'TVSHOW_START_FETCHING_CAST';
export const TVSHOW_END_FETCHING_CAST = 'TVSHOW_END_FETCHING_CAST';
export const TVSHOW_ERROR_FETCHING_CAST = 'TVSHOW_ERROR_FETCHING_CAST';
export const TVSHOW_START_FETCHING_RECOMMENDATIONS = 'TVSHOW_START_FETCHING_RECOMMENDATIONS';
export const TVSHOW_END_FETCHING_RECOMMENDATIONS = 'TVSHOW_END_FETCHING_RECOMMENDATIONS';
export const TVSHOW_ERROR_FETCHING_RECOMMENDATIONS = 'TVSHOW_ERROR_FETCHING_RECOMMENDATIONS';
export const TVSHOW_START_FETCHING_VIDEOS = 'TVSHOW_START_FETCHING_VIDEOS';
export const TVSHOW_END_FETCHING_VIDEOS = 'TVSHOW_END_FETCHING_VIDEOS';
export const TVSHOW_ERROR_FETCHING_VIDEOS = 'TVSHOW_ERROR_FETCHING_VIDEOS';
export const TVSHOW_CLEAR_STATE = 'TVSHOW_CLEAR_STATE';

// ACTOR
export const ACTOR_START_FETCHING_INFO = 'ACTOR_START_FETCHING_INFO';
export const ACTOR_END_FETCHING_INFO = 'ACTOR_END_FETCHING_INFO';
export const ACTOR_ERROR_FETCHING_INFO = 'ACTOR_ERROR_FETCHING_INFO';
export const ACTOR_START_FETCHING_CREDITS = 'ACTOR_START_FETCHING_CREDITS';
export const ACTOR_END_FETCHING_CREDITS = 'ACTOR_END_FETCHING_CREDITS';
export const ACTOR_ERROR_FETCHING_CREDITS = 'ACTOR_ERROR_FETCHING_CREDITS';
export const ACTOR_CLEAR_STATE = 'ACTOR_CLEAR_STATE';

// FIRESTORE COLLECTIONS
export const FIRESTORE_ADD_COLLECTION = 'FIRESTORE_ADD_COLLECTION';
export const FIRESTORE_ADD_ITEM_TO_COLLECTION = 'FIRESTORE_ADD_ITEM_TO_COLLECTION';
export const FIRESTORE_REMOVE_ITEM_FROM_COLLECTION = 'FIRESTORE_REMOVE_ITEM_FROM_COLLECTION';
export const FIRESTORE_REMOVE_COLLECTIONS = 'FIRESTORE_REMOVE_COLLECTIONS';